# Site settings
title: Jedelwey
email: jedelwey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tutoriales comodos y practicos sobre instalación de programas, scripts
  y cualquier cosa relacionada con la administración de sistemas operativos.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jedelwey.com" # the base hostname & protocol for your site
twitter_username: jedelwey
github_username:  jedelwey

# Build settings
markdown: kramdown
